#:schema node_modules/wrangler/config-schema.json
name = "lc-create-appointment"
main = "src/index.ts"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]

[vars]
LEADCONNECTOR_URL="https://services.leadconnectorhq.com"

[[routes]]
pattern = "https://api.thrue.ai/lc/create-appointment/*"
zone_name = "thrue.ai"

[[routes]]
pattern = "https://api.thrue.ai/lc-create-appointment/*"
zone_name = "thrue.ai"